---
title: "Semester Overview"
format:
  html:
    toc: true
    number-sections: true
params:
  semester: null
  required_weeks: 9
  require_obs_per_week: 4
editor_options: 
  chunk_output_type: console
---

```{r echo=F, results='hide', message=FALSE, output='hide'}
library(tidyverse)
library(DT)
library(ggplot2)
```

## Semester: `r params$semester`

There are `r nrow(ds)` total observations this semester.

**Number of observers:** `r n_distinct(ds$observedby_person_id)`  
**Total observations:** `r nrow(ds)`

[Download CSV](https://github.com/AdamWilsonLabEDU/campus_phenology/releases/download/npn-data/npn_obs_network-891_semester-`r params$semester`.csv)


## Observer Overview

```{r  echo=F}
ds %>%
  group_by(observedby_person_id) %>%
  summarize(total_obs = n()) %>%
  mutate(link = paste0("<a href='student_", params$semester, "_", observedby_person_id, ".html'>See details</a>")) %>%
  select(NNID = observedby_person_id, total_obs, link) %>%
  datatable(escape = FALSE)
```


## Weekly Observations Heatmap

```{r  echo=F, fig.height=12 }
if(nrow(ds) > 0) {
  ds %>%
    group_by(observedby_person_id, observation_week) %>%
    summarize(total_obs = n(), .groups = "drop") %>%
    ggplot(aes(x = observation_week, y = as.factor(observedby_person_id), fill = total_obs)) +
    geom_tile() +
    scale_fill_viridis_c(trans = "log1p") +
    xlab("Week of Semester") +
    ylab("Observer") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
}
```



## Phenology Observations by Species

```{r  echo=F}
if(nrow(ds) > 0) {
  ds %>%
    group_by(common_name) %>%
    summarize(n_obs = n()) %>%
    ggplot(aes(x = reorder(common_name, n_obs), y = n_obs)) +
    geom_col() +
    coord_flip() +
    ylab("Number of Observations") +
    xlab("Species")
}
```


